# $Id: Makefile,v 0.1 2013/4/28 2:34:00 dan Exp $
#
PYTHON=`which python`
DESTDIR=/
all:
		@echo "make install - Install on local system"
	
		@echo "make buildsrc - Generate a deb source package"

		@echo "make clean - Get rid of scratch and byte files"

install:
		$(PYTHON) setup.py install

buildsrc:
#		debuild -i -us -uc -b

		dpkg-buildpackage -i -I -rfakeroot
clean:
		$(PYTHON) setup.py clean

