Document: plover
Title: Debian plover Manual
Author: <insert document author here>
Abstract: This manual describes what plover is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/plover/plover.sgml.gz

Format: postscript
Files: /usr/share/doc/plover/plover.ps.gz

Format: text
Files: /usr/share/doc/plover/plover.text.gz

Format: HTML
Index: /usr/share/doc/plover/html/index.html
Files: /usr/share/doc/plover/html/*.html
